[2025-04-06T02:33:46.487+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T02:33:46.541+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_data.fetching_and_modelling scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-06T02:33:46.575+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_data.fetching_and_modelling scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-06T02:33:46.576+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-06T02:33:46.651+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): fetching_and_modelling> on 2025-04-05 00:00:00+00:00
[2025-04-06T02:33:46.665+0000] {standard_task_runner.py:72} INFO - Started process 141 to run task
[2025-04-06T02:33:46.673+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_and_store_data', 'fetching_and_modelling', 'scheduled__2025-04-05T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/reverse_etl_dag.py', '--cfg-path', '/tmp/tmp72k5o3en']
[2025-04-06T02:33:46.679+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask fetching_and_modelling
[2025-04-06T02:33:46.846+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_data.fetching_and_modelling scheduled__2025-04-05T00:00:00+00:00 [running]> on host 830eaf47e7f8
[2025-04-06T02:33:47.126+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_and_store_data' AIRFLOW_CTX_TASK_ID='fetching_and_modelling' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T00:00:00+00:00'
[2025-04-06T02:33:47.127+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-06T02:33:47.146+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-06T02:33:47.148+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', ' cd /usr/local/airflow/workfile && python datamodelling.py']
[2025-04-06T02:33:47.163+0000] {subprocess.py:99} INFO - Output:
[2025-04-06T02:33:54.432+0000] {subprocess.py:106} INFO - [2025-04-06T02:33:54.429+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-04-06T02:37:26.709+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-06T02:37:26.809+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-06T02:37:26.810+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_and_store_data, task_id=fetching_and_modelling, run_id=scheduled__2025-04-05T00:00:00+00:00, execution_date=20250405T000000, start_date=20250406T023346, end_date=20250406T023726
[2025-04-06T02:37:27.009+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-06T02:37:27.090+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-04-06T02:37:27.092+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-06T02:37:27.115+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
